In [ ]:
import os
os.listdir('.')

# os.chdir('C:/Users/0974/Documents/Google Colab/Datasets')

['california_housing_train.csv',
 'heart.csv',
 'iris.csv',
 'pima-indians-diabetes.csv',
 'sonar.csv']

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sb

In [ ]:
filename = 'sonar.csv'

dataset = pd.read_csv(filename)

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 208 entries, 0 to 207
Data columns (total 61 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   V1      208 non-null    float64
 1   V2      208 non-null    float64
 2   V3      208 non-null    float64
 3   V4      208 non-null    float64
 4   V5      208 non-null    float64
 5   V6      208 non-null    float64
 6   V7      208 non-null    float64
 7   V8      208 non-null    float64
 8   V9      208 non-null    float64
 9   V10     208 non-null    float64
 10  V11     208 non-null    float64
 11  V12     208 non-null    float64
 12  V13     208 non-null    float64
 13  V14     208 non-null    float64
 14  V15     208 non-null    float64
 15  V16     208 non-null    float64
 16  V17     208 non-null    float64
 17  V18     208 non-null    float64
 18  V19     208 non-null    float64
 19  V20     208 non-null    float64
 20  V21     208 non-null    float64
 21  V22     208 non-null    float64
 22  V23     208 non-null    float64
 23  V24     208 non-null    float64
 24  V25     208 non-null    float64
 25  V26     208 non-null    float64
 26  V27     208 non-null    float64
 27  V28     208 non-null    float64
 28  V29     208 non-null    float64
 29  V30     208 non-null    float64
 30  V31     208 non-null    float64
 31  V32     208 non-null    float64
 32  V33     208 non-null    float64
 33  V34     208 non-null    float64
 34  V35     208 non-null    float64
 35  V36     208 non-null    float64
 36  V37     208 non-null    float64
 37  V38     208 non-null    float64
 38  V39     208 non-null    float64
 39  V40     208 non-null    float64
 40  V41     208 non-null    float64
 41  V42     208 non-null    float64
 42  V43     208 non-null    float64
 43  V44     208 non-null    float64
 44  V45     208 non-null    float64
 45  V46     208 non-null    float64
 46  V47     208 non-null    float64
 47  V48     208 non-null    float64
 48  V49     208 non-null    float64
 49  V50     208 non-null    float64
 50  V51     208 non-null    float64
 51  V52     208 non-null    float64
 52  V53     208 non-null    float64
 53  V54     208 non-null    float64
 54  V55     208 non-null    float64
 55  V56     208 non-null    float64
 56  V57     208 non-null    float64
 57  V58     208 non-null    float64
 58  V59     208 non-null    float64
 59  V60     208 non-null    float64
 60  Class   208 non-null    int64
dtypes: float64(60), int64(1)
memory usage: 99.2 KB

In [ ]:
dataset.describe()

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,...,V52,V53,V54,V55,V56,V57,V58,V59,V60,Class
count,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,...,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000
mean,0.029164,0.038437,0.043832,0.053892,0.075202,0.104570,0.121747,0.134799,0.178003,0.208259,...,0.013420,0.010709,0.010941,0.009290,0.008222,0.007820,0.007949,0.007941,0.006507,0.466346
std,0.022991,0.032960,0.038428,0.046528,0.055552,0.059105,0.061788,0.085152,0.118387,0.134416,...,0.009634,0.007060,0.007301,0.007088,0.005736,0.005785,0.006470,0.006181,0.005031,0.500070
min,0.001500,0.000600,0.001500,0.005800,0.006700,0.010200,0.003300,0.005500,0.007500,0.011300,...,0.000800,0.000500,0.001000,0.000600,0.000400,0.000300,0.000300,0.000100,0.000600,0.000000
25%,0.013350,0.016450,0.018950,0.024375,0.038050,0.067025,0.080900,0.080425,0.097025,0.111275,...,0.007275,0.005075,0.005375,0.004150,0.004400,0.003700,0.003600,0.003675,0.003100,0.000000
50%,0.022800,0.030800,0.034300,0.044050,0.062500,0.092150,0.106950,0.112100,0.152250,0.182400,...,0.011400,0.009550,0.009300,0.007500,0.006850,0.005950,0.005800,0.006400,0.005300,0.000000
75%,0.035550,0.047950,0.057950,0.064500,0.100275,0.134125,0.154000,0.169600,0.233425,0.268700,...,0.016725,0.014900,0.014500,0.012100,0.010575,0.010425,0.010350,0.010325,0.008525,1.000000
max,0.137100,0.233900,0.305900,0.426400,0.401000,0.382300,0.372900,0.459000,0.682800,0.710600,...,0.070900,0.039000,0.035200,0.044700,0.039400,0.035500,0.044000,0.036400,0.043900,1.000000

In [ ]:
print(dataset['Class'].value_counts())

0    111
1     97
Name: Class, dtype: int64

In [ ]:
dataset.columns

Index(['V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10', 'V11',
       'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20', 'V21',
       'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'V29', 'V30', 'V31',
       'V32', 'V33', 'V34', 'V35', 'V36', 'V37', 'V38', 'V39', 'V40', 'V41',
       'V42', 'V43', 'V44', 'V45', 'V46', 'V47', 'V48', 'V49', 'V50', 'V51',
       'V52', 'V53', 'V54', 'V55', 'V56', 'V57', 'V58', 'V59', 'V60', 'Class'],
      dtype='object')

In [ ]:
for i in dataset.columns:
    print(i, ': ', len(dataset[dataset[i].isnull()][i]))

V1 :  0
V2 :  0
V3 :  0
V4 :  0
V5 :  0
V6 :  0
V7 :  0
V8 :  0
V9 :  0
V10 :  0
V11 :  0
V12 :  0
V13 :  0
V14 :  0
V15 :  0
V16 :  0
V17 :  0
V18 :  0
V19 :  0
V20 :  0
V21 :  0
V22 :  0
V23 :  0
V24 :  0
V25 :  0
V26 :  0
V27 :  0
V28 :  0
V29 :  0
V30 :  0
V31 :  0
V32 :  0
V33 :  0
V34 :  0
V35 :  0
V36 :  0
V37 :  0
V38 :  0
V39 :  0
V40 :  0
V41 :  0
V42 :  0
V43 :  0
V44 :  0
V45 :  0
V46 :  0
V47 :  0
V48 :  0
V49 :  0
V50 :  0
V51 :  0
V52 :  0
V53 :  0
V54 :  0
V55 :  0
V56 :  0
V57 :  0
V58 :  0
V59 :  0
V60 :  0
Class :  0

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

feature = dataset.drop(['Class'], axis=1)
label = dataset['Class']

feature_scaled = scaler.fit_transform(feature.values)

data_feature = pd.DataFrame(feature_scaled, columns=feature.columns)

In [ ]:
from sklearn.model_selection import train_test_split

feature_train, feature_test, label_train, label_test = train_test_split(data_feature, label, test_size=0.25, random_state=4)

In [ ]:
from imblearn.over_sampling import SMOTE
smt = SMOTE()
feature_train, label_train = smt.fit_sample(feature_train, label_train)
np.bincount(label_train)

array([80, 80], dtype=int64)

In [ ]:
from sklearn.metrics import f1_score, precision_score, recall_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.svm import LinearSVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
import xgboost

In [ ]:
names = ["Random Forest Classifier estimator 20", "Random Forest Classifier estimator 40","Random Forest Classifier estimator 60","Random Forest Classifier estimator 80","SVM RBF","SVM Linear","SVM Polynomial", "Linear SVC", "K-Nearest Neighbors k=1", "K-Nearest Neighbors k=3", "K-Nearest Neighbors k=5", "K-Nearest Neighbors k=7", "K-Nearest Neighbors k=9", "K-Nearest Neighbors k=11", "K-Nearest Neighbors k=13", "K-Nearest Neighbors k=15", "Decision Tree Classifier", "Neural Network Classifier", "Ada Boost Classifier", "Naive Bayes", "QDA"]

classifiers = [RandomForestClassifier(n_estimators=20 , bootstrap=True, max_features="sqrt"),
RandomForestClassifier(n_estimators =40 , bootstrap=True, max_features="sqrt"),
RandomForestClassifier(n_estimators =60 , bootstrap=True, max_features="sqrt"),
RandomForestClassifier(n_estimators =80 , bootstrap=True, max_features="sqrt"),
SVC(kernel='rbf'),
SVC(kernel='linear'),
SVC(kernel='poly'),
LinearSVC(),
KNeighborsClassifier(n_neighbors=1),
KNeighborsClassifier(n_neighbors=3),
KNeighborsClassifier(n_neighbors=5),
KNeighborsClassifier(n_neighbors=7),
KNeighborsClassifier(n_neighbors=9),
KNeighborsClassifier(n_neighbors=11),
KNeighborsClassifier(n_neighbors=13),
KNeighborsClassifier(n_neighbors=15),
DecisionTreeClassifier(max_depth=5),
MLPClassifier(alpha=1, max_iter=1000),
AdaBoostClassifier(n_estimators=50, learning_rate=1),
GaussianNB(),
QuadraticDiscriminantAnalysis()
 ]

In [ ]:
def nClassifier(name, classifier):
    for n in range(len(name)):
        classifier[n].fit(feature_train, label_train)
        label_pred = classifier[n].predict(feature_test)
        print('Accuracy of', name[n], 'on test set: {:.3f}'.format(classifier[n].score(feature_test, label_test)))
        print('F1 Score: {:.3f}'.format(f1_score(label_test, label_pred, average="macro")))
        print('Precision Score: {:.3f}'.format(precision_score(label_test, label_pred, average="macro")))
        print('Recall Score: {:.3f}'.format(recall_score(label_test, label_pred, average="macro")))
        print(" ")
    return

In [ ]:
nClassifier(names, classifiers)

Accuracy of Random Forest Classifier estimator 20 on test set: 0.865
F1 Score: 0.859
Precision Score: 0.863
Recall Score: 0.856

Accuracy of Random Forest Classifier estimator 40 on test set: 0.846
F1 Score: 0.838
Precision Score: 0.845
Recall Score: 0.833

Accuracy of Random Forest Classifier estimator 60 on test set: 0.865
F1 Score: 0.856
Precision Score: 0.871
Recall Score: 0.849

Accuracy of Random Forest Classifier estimator 80 on test set: 0.865
F1 Score: 0.856
Precision Score: 0.871
Recall Score: 0.849

Accuracy of SVM RBF on test set: 0.923
F1 Score: 0.917
Precision Score: 0.943
Recall Score: 0.905

Accuracy of SVM Linear on test set: 0.788
F1 Score: 0.779
Precision Score: 0.781
Recall Score: 0.776

Accuracy of SVM Polynomial on test set: 0.923
F1 Score: 0.919
Precision Score: 0.928
Recall Score: 0.912

Accuracy of Linear SVC on test set: 0.769
F1 Score: 0.760
Precision Score: 0.760
Recall Score: 0.760

Accuracy of K-Nearest Neighbors k=1 on test set: 0.808
F1 Score: 0.793
Precision Score: 0.812
Recall Score: 0.785

Accuracy of K-Nearest Neighbors k=3 on test set: 0.827
F1 Score: 0.811
Precision Score: 0.840
Recall Score: 0.801

Accuracy of K-Nearest Neighbors k=5 on test set: 0.846
F1 Score: 0.830
Precision Score: 0.872
Recall Score: 0.817

Accuracy of K-Nearest Neighbors k=7 on test set: 0.846
F1 Score: 0.830
Precision Score: 0.872
Recall Score: 0.817

Accuracy of K-Nearest Neighbors k=9 on test set: 0.846
F1 Score: 0.838
Precision Score: 0.845
Recall Score: 0.833

Accuracy of K-Nearest Neighbors k=11 on test set: 0.846
F1 Score: 0.834
Precision Score: 0.855
Recall Score: 0.825

Accuracy of K-Nearest Neighbors k=13 on test set: 0.769
F1 Score: 0.751
Precision Score: 0.768
Recall Score: 0.745

Accuracy of K-Nearest Neighbors k=15 on test set: 0.788
F1 Score: 0.774
Precision Score: 0.786
Recall Score: 0.769

Accuracy of Decision Tree Classifier on test set: 0.788
F1 Score: 0.774
Precision Score: 0.786
Recall Score: 0.769

Accuracy of Neural Network Classifier on test set: 0.885
F1 Score: 0.876
Precision Score: 0.899
Recall Score: 0.865

Accuracy of Ada Boost Classifier on test set: 0.827
F1 Score: 0.825
Precision Score: 0.827
Recall Score: 0.839

Accuracy of Naive Bayes on test set: 0.654
F1 Score: 0.653
Precision Score: 0.694
Recall Score: 0.687

Accuracy of QDA on test set: 0.750
F1 Score: 0.742
Precision Score: 0.741
Recall Score: 0.744

In [ ]:
Akurasi tertinggi ditemukan pada SVM RBF, SVM Polynomial sebesar 0.923